# Generated by Django 4.2.7 on 2024-04-08 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 8, 12, 32, 42, 639563, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
