# Generated by Django 4.2.7 on 2024-04-13 06:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('typ', models.CharField(default='message', max_length=150)),
                ('sent', models.TextField(blank=True, null=True)),
                ('received', models.TextField(blank=True, null=True)),
                ('cost', models.IntegerField(default=0)),
                ('unique_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='clients',
        ),
        migrations.AddField(
            model_name='account',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roommatch',
            name='ai_response',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='text_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 13, 6, 41, 33, 396313, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='aichat',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to='app.roommatch'),
        ),
        migrations.AddField(
            model_name='account',
            name='ai_chats',
            field=models.ManyToManyField(blank=True, related_name='clients', to='app.aichat'),
        ),
    ]
