# Generated by Django 4.2.7 on 2024-04-13 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aichat_remove_account_clients_account_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichat',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 13, 21, 33, 28, 486798, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
