# Generated by Django 4.2.7 on 2024-04-23 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_audio_created_at_image_created_at_product_typ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 23, 4, 25, 8, 813687, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
