# Generated by Django 4.2.7 on 2024-10-18 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_created_at_alter_user_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos', to='app.video'),
        ),
        migrations.AlterField(
            model_name='roommatch',
            name='why',
            field=models.TextField(default='Bienvenue'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 14, 40, 40, 425886, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
