# Generated by Django 4.2.7 on 2024-10-18 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 18, 14, 51, 41, 951761, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
